### ISSUE TITLE
Pakiet figure

### ISSUE THREAD

**Issue by JaRutkowski** [KrKalita/test#6]
Utworzyć nowy pakiet o nazwie com.javafee.figure zawierający następujące klasy wraz z ich implementacją:
- Circle
- Triangle
- Square
- Rectangle

Każda z klas ma w podstawowy sposób opisywać obiekt figury której dotyczy. Obowiązkowo mają zawierać metody:
- getField()
- getCircuit()

Należy użyć hierarchii klas i zastosować takie paradygmaty programowania obiektowego jak hermetyzacja, polimorfizm, dziedziczenie.

Podpowiedź: metody getField(), getCircuit() mają być przesłaniać te z klasy bazowej, zwrócić uwagę na przykładowe użycie klas - dostępne są tam odpowiedzi dot. implementowanych metod. Po zaimplementowaniu issue, przykładowy kod powinien działać poprawnie.

Przykładowe użycie napisanych klas:
```
Circle circle = new Circle();
circle.setRadius(2.0);
System.out.println(circle.getField());

Traingle triangle = new Triangle(2.0, 3.0, 3.0);
System.out.println(triangle.getCircuit());

Square square = new Square();
square.setSide(2.0);
System.out.println(square.getField());

Rectangle rectangle = new Rectangle();
rectangle.setShortSide(2.0);
rectangle.setLongSide(3.0);
System.out.println(rectangle.getCircuit());
```

Podsumowanie:
- [x] Circle
- [x] Triangle
- [x] Square
- [x] Rectangle

Stwórz do zadania gałąź o nazwie #6_Pakiet_figure
Następnie pobierz ją z poziomu Eclipse'a za pomocą Fetch from Upstream
Wykonaj zmianę
Zrób commit & push
W GitHub'ie wykonaj 'createPullRequest' (będzie dostępne w zakładce 'code' - zielony przycisk)
Zatwierdź
Dokonaj merge (zielony przycisk)
Przełącz się w eclips'e na master'a (po wcześniejszym fetch'u!).

**Comment by JaRutkowski** [comment]
Uwagi po weryfikacji:

1. Błędna realizacja polimorfizmu w kontekście metody getField() oraz getCircuit(), klasa bazowa powinna posiadać pustą implementację, za którą odpowiedzialne są wyspecjalizowane klasy pochodne, dziedziczące po klasie Figure (z godnie z tym co w poleceniu: "metody getField(), getCircuit() mają przesłaniać te z klasy bazowej").
2. Metody getField(), getCircle() powinny zwracać obliczoną wartość w postaci Double.
3. Niezrozumiała idea metody podstawyFigura().
4. Niezastosowanie się do anglojęzycznej konwencji np. w klasie Circle pole nazywa się promien zamiast radius, w Square setSide etc., poprawić również notację typu camel w metodach (getRadius zamiast getradius) oraz zadbać o formatowanie.
5. Niepotrzebnie zacommitowana klasa testowa z metodą main() MainFigure.

Otworzyć ponownie zgłoszenie, przywrócić gałąź, poprawić błędy.

**Comment by KrKalita** [comment]
Poprawa po weryfikacji.
